changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: What's New
      labels:
        - feature
    - title: Bug fixes
      labels:
        - bug
    - title: What's Changed
      labels:
        - "*"
